[customizations.installer.modules]
enable = [
  "org.fedoraproject.Anaconda.Modules.Storage",      # Disk partitioning
  "org.fedoraproject.Anaconda.Modules.Network",      # Network config
  "org.fedoraproject.Anaconda.Modules.Users",        # User account creation
  "org.fedoraproject.Anaconda.Modules.Timezone",     # Time/timezone
  "org.fedoraproject.Anaconda.Modules.Localization", # Keyboard/language
  "org.fedoraproject.Anaconda.Modules.Security",     # SELinux, security policies
  "org.fedoraproject.Anaconda.Modules.Services",      # systemd services
  "org.fedoraproject.Anaconda.Modules.Runtime"      
]
disable = [
  "org.fedoraproject.Anaconda.Modules.Subscription"  # Not needed unless RHEL
]
